fix: Add determine console code page encoding
StephLin/click-pwsh pull request #1
Opened 2024-12-23 23:37 UTC by IvolgaDmitriy

Hello!

In my case, the first installation failed:
```bash
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x84 in position 24: invalid start byte
```
As it turned out, the console uses a different encoding than the one specified in `chcp`, despite using `UTF-8`. To fix this, I added explicit page code to specify the desired encoding for the `.encode()` function.

I hope you find these changes useful. Thank you so much for this package. It helped a lot for my app.

2025-01-11 06:51 UTC, StephLin requested changes
Hi @IvolgaDmitriy,

Thanks for your contribution and sorry for my delayed response. Please take a look at my review. Thank you!

2025-01-11 06:51 UTC, StephLin commented on click_pwsh/__main__.py
> +    encoding = sp.run('pwsh -c "(chcp | Out-String).Split(\' \')[-1].Trim()"', shell=False, capture_output=True)
Can we just use [`locale.getpreferredencoding(False)`](https://docs.python.org/3/library/locale.html#locale.getpreferredencoding) or [`locale.getencoding()`](https://docs.python.org/3/library/locale.html#locale.getencoding) (Python >= 3.11)?

2025-01-12 10:38 UTC, IvolgaDmitriy commented on click_pwsh/__main__.py
> +    encoding = sp.run('pwsh -c "(chcp | Out-String).Split(\' \')[-1].Trim()"', shell=False, capture_output=True)
I started with this idea, but it turned out that the `locale.getpreferredencoding(False)` or `locale.getencoding()` methods are tied to the system's locale configuration, and `chcp` only reflects the encoding used by the terminal session, which may not match the system's encoding.

2025-01-12 14:37 UTC, StephLin commented on click_pwsh/__main__.py
> +    encoding = sp.run('pwsh -c "(chcp | Out-String).Split(\' \')[-1].Trim()"', shell=False, capture_output=True)
Cool. Got it.

2025-01-12 14:38 UTC, merged

2025-01-12 14:40 UTC, StephLin commented
Thanks @IvolgaDmitriy!